version: '3.4'

services:
  apigateway:
    image: apigateway
    build:
      context: api-gateway
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
